{
 "title": "APPLICATION_NAME",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nombre de lignes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date,\n  (SUM(addition) OVER (ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) -\n   SUM(deletion) OVER (ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) AS total_lines\nFROM \"APPLICATION_NAME\"\nORDER BY date;\n"
    }
   ]
  },
  {
   "title": "Activite",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, COUNT(id) AS \"commit\" FROM \"APPLICATION_NAME\" GROUP BY date"
    }
   ]
  },
  {
   "title": "Ajouts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT SUM(addition), author FROM \"APPLICATION_NAME\" GROUP BY author ORDER BY SUM(addition) DESC LIMIT 3 "
    }
   ]
  },
  {
   "title": "Suppressions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT author, SUM(deletion) FROM \"APPLICATION_NAME\" GROUP BY author ORDER BY SUM(deletion) DESC LIMIT 3 "
    }
   ]
  }
 ]
}