version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: stat
      POSTGRES_USER: grafana_user
      POSTGRES_PASSWORD: grafana_password
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - postgres
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      #- ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      #- ./dashboard:/etc/grafana/provisioning/dashboards

volumes:
  postgres_data:
  grafana_data:
