apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: grafana_user
    secureJsonData:
      password: grafana_password
    jsonData:
      database: stat
      sslmode: "disable"
    isDefault: true
